server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:${AUTH_DB_PORT}/${AUTH_DB_NAME}
    username: ${AUTH_DB_USER}
    password: ${AUTH_DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

logging:
  level:
    com.coolonlineshop.auth: DEBUG
