server:
  port: 8083

spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog_db
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

logging:
  level:
    com.coolonlineshop.catalog: DEBUG
