server:
  port: 8083

spring:
  application:
    name: catalog-service

  datasource:
    url: jdbc:postgresql://localhost:${CATALOG_DB_PORT}/${CATALOG_DB_NAME}
    username: ${CATALOG_DB_USER}
    password: ${CATALOG_DB_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

logging:
  level:
    com.coolonlineshop.catalog: DEBUG
