server:
  port: 8085

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

logging:
  level:
    com.coolonlineshop.order: DEBUG
