server:
  port: 8085

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:${ORDER_DB_PORT}/${ORDER_DB_NAME}
    username: ${ORDER_DB_USER}
    password: ${ORDER_DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

cart-service:
  base-url: ${CART_SERVICE_BASE_URL}
  connect-timeout: ${CART_SERVICE_CONNECT_TIMEOUT}
  read-timeout: ${CART_SERVICE_READ_TIMEOUT}

catalog-service:
  base-url: ${CATALOG_SERVICE_BASE_URL}
  connect-timeout: ${CATALOG_SERVICE_CONNECT_TIMEOUT}
  read-timeout: ${CATALOG_SERVICE_READ_TIMEOUT}

logging:
  level:
    com.coolonlineshop.order: DEBUG
