server:
  port: ${CART_SERVICE_PORT}

spring:
  application:
    name: cart-service
  data:
    redis:
      host: ${CART_REDIS_HOST}
      port: ${CART_REDIS_PORT}

catalog-service:
  base-url: ${CATALOG_SERVICE_BASE_URL}
  connect-timeout: ${CATALOG_SERVICE_CONNECT_TIMEOUT:5s}
  read-timeout: ${CATALOG_SERVICE_READ_TIMEOUT:10s}

logging:
  level:
    com.coolonlineshop.cart: DEBUG
