server:
  port: 8084

spring:
  application:
    name: cart-service
  data:
    redis:
      host: ${CART_REDIS_HOST}
      port: ${CART_REDIS_PORT}

logging:
  level:
    com.coolonlineshop.cart: DEBUG
