server:
  port: 8084

spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:postgresql://localhost:5432/cart_db
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    com.coolonlineshop.cart: DEBUG
